PracticaMvcCore2Iniciales/Controllers/LibrosController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2Iniciales.Extensions;
using PracticaMvcCore2Iniciales.Models;
using PracticaMvcCore2Iniciales.Repositories;

namespace PracticaMvcCore2Iniciales.Controllers
{
    public class LibrosController : Controller
    {
        private RepositoryLibros repo;

        public LibrosController(RepositoryLibros repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            List<Libro> libros = await this.repo.GetLibrosAsync();
            return View(libros);
        }


        public async Task<IActionResult> Details(int idlibro)
        {
            Libro libro = await this.repo.FindLibroAsync(idlibro);
            return View(libro);
        }


        //------------------sesion-----------------

        public async Task<IActionResult> SessionLibros
    (int? idlibro)
        {
            if (idlibro != null)
            {
                //BUSCAMOS AL libro
                Libro libro = await this.repo.FindLibroAsync(idlibro.Value);
                //EN SESSION ALMACENAREMOS UN CONJUNTO DE EMPLEADOS
                List <Libro> librosList;
                //DEBEMOS PREGUNTAR SI TENEMOS libro DENTRO DE 
                //SESSION
                if (HttpContext.Session.GetObject<List<Libro>>("LIBROS") != null)
                {
                    //SI YA TENEMOS EMPLEADOS, LOS RECUPERAMOS DE SESSION
                    librosList =
                        HttpContext.Session.GetObject<List<Libro>>("LIBROS");
                }
                else
                {
                    //SI NO TENEMOS EMPLEADOS, CREAMOS LA COLECCION PARA 
                    //ALMACENAR EL PRIMER EMPLEADO
                    librosList = new List<Libro>();
                }
                //ALMACENAMOS EL NUEVO libro EN SESSION
                librosList.Add(libro);
                //GUARDAMOS LA COLECCION DENTRO DE SESSION
                HttpContext.Session.SetObject("LIBROS", librosList);
                ViewData["MENSAJE"] = "Libro " + libro.Titulo
                    + " almacenado correctamente";
            }
            List<Libro> libros =
                await this.repo.GetLibrosAsync();
            return View(libros);
        }

        public IActionResult LibrosAlmacenados()
        {
            return View();
        }


        public async Task<IActionResult>
            LibrosAlmacenadosOk(int? ideliminar)
        {
            //DEBEMOS RECUPERAR LOS EMPLEADOS QUE ESTEN DENTRO 
            //DE LA COLECCION DE SESSION
            //RECUPERAMOS LOS DATOS DE LA COLECCION DE IDS DE SESSION
            List<int> idsLibros =
                HttpContext.Session.GetObject<List<int>>("IDSLIBROS");
            if (idsLibros != null)
            {
                //DEBEMOS ELIMINAR DE SESSION
                if (ideliminar != null)
                {
                    //NOS HAN ENVIADO UN DATO PARA ELIMINARLO DE SESSION
                    idsLibros.Remove(ideliminar.Value);
                    //DEBEMOS PREGUNTAR SI YA NO TENEMOS EMPLEADOS EN LA 
                    //COLECCION
                    if (idsLibros.Count == 0)
                    {
                        //ELIMINAMOS DIRECTAMENTE SESSION CON SU KEY
                        HttpContext.Session.Remove("IDSLIBROS");
                    }
                    else
                    {
                        //ALMACENAMOS DE NUEVO LOS DATOS EN SESSION
                        HttpContext.Session.SetObject("IDSLIBROS", idsLibros);
                    }
                }
                List<Libro> libros = await
                    this.repo.GetLibrosSessionAsync(idsLibros);
                return View(libros);
            }
            return View();
        }



        public async Task<IActionResult> SessionLibrosOk(int? idlibro)
        {
            if (idlibro != null)
            {
                //ALMACENAREMOS LO MINIMO DEL OBJETO, UNA COLECCION INT
                List<int> idsLibros;
                if (HttpContext.Session.GetString("IDSLIBROS") == null)
                {
                    //TODAVIA NO TENEMOS DATOS EN SESSION Y CREAMOS LA COLECCION
                    idsLibros = new List<int>();
                }
                else
                {
                    //RECUPERAMOS LA COLECCION DE Ids DE SESSION
                    idsLibros =
                        HttpContext.Session.GetObject<List<int>>("IDSLIBROS");
                }
                //ALMACENAMOS EL ID DEL EMPLEADO EN LA COLECCION
                idsLibros.Add(idlibro.Value);
                //ALMACENAMOS LA COLECCION EN SESSION CON LOS CAMBIOS REALIZADOS
                HttpContext.Session.SetObject("IDSLIBROS", idsLibros);
                ViewData["MENSAJE"] = "LIBROS almacenados: "
                    + idsLibros.Count;
            }
            //COMPROBAMOS SI TENEMOS ALGO EN SESSION
            List<int> ids = HttpContext.Session.GetObject<List<int>>("IDSLIBROS");
            if (ids == null)
            {
                List<Libro> libros = await this.repo.GetLibrosAsync();
                return View(libros);
            }
            else
            {
                List<Libro> libros = await
                    this.repo.GetLibrosNotSessionAsync(ids);
                return View(libros);
            }
        }











    }
}

PracticaMvcCore2Iniciales/Controllers/ManagedController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2Iniciales.Repositories;
using System.Security.Claims;
using PracticaMvcCore2Iniciales.Models;

namespace PracticaMvcCore2Iniciales.Controllers
{
    public class ManagedController : Controller
    {
        private RepositoryUsuarios repo;

        public ManagedController(RepositoryUsuarios repo)
        {
            this.repo = repo;
        }

        //--------------------
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login
    (string email, string password)
        {
           
            Usuario usuario = await
                this.repo.LogInEmpleadoAsync(email, password);
            if (usuario != null)
            {
                //SEGURIDAD
                ClaimsIdentity identity =
                    new ClaimsIdentity(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        ClaimTypes.Name, ClaimTypes.Role);
                //CREAMOS EL CLAIM PARA EL NOMBRE (email)
                Claim claimName =
                    new Claim(ClaimTypes.Name, usuario.Email);
                identity.AddClaim(claimName);

                //APELLIDOS
                Claim claimApellido =
                    new Claim("Apellidos", usuario.Apellidos);
                identity.AddClaim(claimApellido);
                //foto
                Claim claimFoto =
                    new Claim("Foto", usuario.Foto);
                identity.AddClaim(claimFoto);
                //nombre
                Claim claimNombre =
                    new Claim("Nombre", usuario.Nombre);
                identity.AddClaim(claimNombre);
                //idusuario
                Claim claimIdUsuario =
                    new Claim(ClaimTypes.NameIdentifier, usuario.IdUsuario.ToString());
                identity.AddClaim(claimIdUsuario);





                //COMO POR AHORA NO VOY A UTILIZAR NI SE UTILIZAR ROLES
                //NO LO INCLUIMOS
                ClaimsPrincipal userPrincipal =
                    new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(
                    CookieAuthenticationDefaults.AuthenticationScheme,
                    userPrincipal);
                //LO VAMOS A LLEVAR A UNA VISTA QUE TODAVIA NO TENEMOS
                //QUE SERA EL PERFIL DEL EMPLEADO
                return RedirectToAction("PerfilUsuario", "Usuarios");
            }
            else
            {
                ViewData["MENSAJE"] = "Usuario/Password incorrectos";
                return View();
            }
        }






        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync
                (CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }










    }
}

PracticaMvcCore2Iniciales/Controllers/PedidosViewController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2Iniciales.Filters;
using PracticaMvcCore2Iniciales.Models;
using PracticaMvcCore2Iniciales.Repositories;
using System.Security.Claims;

namespace PracticaMvcCore2Iniciales.Controllers
{
    public class PedidosViewController : Controller
    {
        private RepositoryVistaPedidos repo;

        public PedidosViewController(RepositoryVistaPedidos repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            List<VistaPedido> model = await this.repo.GetPedidosAsync();
            return View(model);
        }

        [AuthorizeUsuarios]
        public async Task<IActionResult> PedidosUsuario()
        {
            // Obtener el ClaimsPrincipal del usuario actual
            ClaimsPrincipal user = this.User;

            // Obtener los pedidos del usuario actual
            var model = await this.repo.GetPedidosUserAsync(user);

            return View(model);
        }







    }
}

PracticaMvcCore2Iniciales/ViewComponents/MenuLibrosViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2Iniciales.Models;
using PracticaMvcCore2Iniciales.Repositories;

namespace PracticaMvcCore2Iniciales.ViewComponents
{
    public class MenuLibrosViewComponent : ViewComponent
    {
        private RepositoryGeneros repo;

        public MenuLibrosViewComponent(RepositoryGeneros repo)
        {
            this.repo = repo;
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<Genero> generos = await this.repo.GetGenerosAsync();
            return View(generos);
        }

        

    }
}

PracticaMvcCore2Iniciales/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PracticaMvcCore2Iniciales</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PracticaMvcCore2Iniciales.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PracticaMvcCore2Iniciales</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">




                        @await Component.InvokeAsync("MenuLibros")
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuarios" asp-action="Index">Usuarios sin proteccion</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="SessionLibrosOk">LibrosBUENO</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PedidosView" asp-action="Index">PedidosTotales</a>
                        </li>


                  @*       <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="Index">LibrosNORMAL</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="SessionLibros">SessionLibros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="LibrosAlmacenados">LibrosAlmacenados</a>
                        </li> *@



                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Libros" asp-action="LibrosAlmacenadosOk">CARRITO</a>
                        </li>
                       
                        <partial name="_MenuUsuario" />


                      








                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - PracticaMvcCore2Iniciales - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

PracticaMvcCore2Iniciales/Views/Shared/_MenuUsuario.cshtml
@if (Context.User.Identity.IsAuthenticated == false)
{
    //EFECTO OPTICO DEL LOGIN
    <li class="nav-item">
        <a asp-controller="Usuarios"
           asp-action="PerfilUsuario"
           class="nav-link">
            Log In
        </a>
    </li>
}
else
{
    <li class="nav-item">
        <a asp-controller="PedidosView"
           asp-action="PedidosUsuario"
           class="nav-link">
            Tus pedidos <span style="color:blue">

            </span>
        </a>
    </li>
    <li class="nav-item">
        <a asp-controller="Managed"
           asp-action="Logout"
           class="nav-link">
            Log out <span style="color:blue">
               
            </span>
        </a>
    </li>
    <li class="nav-item">
        <a asp-controller="Usuarios"
           asp-action="PerfilUsuario"
           class="nav-link">
            Hola,  @Context.User.FindFirst("Nombre").Value
        </a>
    </li>
}