PracticaMvcCore2Iniciales/Models/Usuario.cs
using PracticaMvcCore2Iniciales.Models;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PracticaMvcCore2Iniciales.Models
{
    [Table("USUARIOS")]
    public class Usuario
    {
        [Key]
        [Column("IdUsuario")]
        public int IdUsuario { get; set; }

        [Column("Nombre")]
        public string Nombre { get; set; }

        [Column("Apellidos")]
        public string Apellidos { get; set; }

        [Column("Email")]
        public string Email { get; set; }

        [Column("Pass")]
        public string Pass { get; set; }

        [Column("Foto")]
        public string Foto { get; set; }
    }
}

PracticaMvcCore2Iniciales/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Mvc;
using PracticaMvcCore2Iniciales.Filters;
using PracticaMvcCore2Iniciales.Models;
using PracticaMvcCore2Iniciales.Repositories;

namespace PracticaMvcCore2Iniciales.Controllers
{
    public class UsuariosController : Controller
    {
        private RepositoryUsuarios repo;

        public UsuariosController(RepositoryUsuarios repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            List<Usuario> usuarios = await this.repo.GetUsuariosAsync();
            return View(usuarios);
        }

        public async Task<IActionResult> Details(int idusuario)
        {
            Usuario usuario = await this.repo.FindUsuarioAsync(idusuario);
            return View(usuario);
        }



        //-----------vistas con seguridad--------------

        [AuthorizeUsuarios]
        public IActionResult PerfilUsuario()
        {
            return View();
        }



    }
}

PracticaMvcCore2Iniciales/Views/Usuarios/Details.cshtml
@model PracticaMvcCore2Iniciales.Models.Usuario

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Usuario</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IdUsuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IdUsuario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellidos)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellidos)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Pass)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Pass)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Foto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Foto)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

PracticaMvcCore2Iniciales/Views/Usuarios/Index.cshtml
@model IEnumerable<PracticaMvcCore2Iniciales.Models.Usuario>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdUsuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellidos)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pass)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Foto)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdUsuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellidos)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Pass)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Foto)
            </td>
            <td>
                    <a asp-controller="Usuarios"
                       asp-action="Details"
                       asp-route-idusuario="@item.IdUsuario"
                       class="btn btn-info">
                        Details
                    </a>
            </td>
        </tr>
}
    </tbody>
</table>

PracticaMvcCore2Iniciales/Views/Usuarios/PerfilUsuario.cshtml
@using System.Security.Claims

<h1>
    Perfil de: @Context.User.Identity.Name
</h1>

<ul class="list-group">
    <li class="list-group-item">
        Nombre: @Context.User.FindFirst("Nombre").Value
    </li>
    <li class="list-group-item">
        Apellido: @Context.User.FindFirst("Apellidos").Value 
    </li>
    <img src="/images/@Context.User.FindFirst("Foto").Value" />
</ul>
<h2>Todos los Claims</h2>
<ul>
    @foreach (Claim claim in Context.User.Claims)
    {
        <li>@claim.Type: <b>@claim.Value</b></li>
    }
</ul>